# Generated by Django 3.1.1 on 2020-11-05 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.TextField(max_length=400, verbose_name='Post')),
                ('Image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='', verbose_name='Post Image')),
                ('DateTime', models.DateTimeField(auto_now=True)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tweet_Name', to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
        ),
    ]
